import Head from "next/head";
import Image from "next/image";
import { Paper } from "@mui/material";
import styles from "@/styles/Home.module.css";

// @component
import { ParentSection } from "@/components";

import { SectionInformation } from "@/data/section";

export default function Home() {
  // console.log(SectionInformation);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Paper
          className="flex flex-row align-middle ml-2 mr-2 mt-28 py-3 px-1"
          elevation={12}
          sx={{ overflowX: "auto" }}
        >
          {SectionInformation.map((data) => {
            return (
              <div key={data.id}>
                <ParentSection
                  id={data.id}
                  name={data.name}
                  personInfo={data.personInfo}
                />
              </div>
            );
          })}
        </Paper>
      </main>
    </>
  );
}
